sudo: required
language: python
python:
- '2.7'
addons:
  ssh_known_hosts: jonathan.me
services: docker
before_install:
- openssl aes-256-cbc -K $encrypted_8fab0ebf337a_key -iv $encrypted_8fab0ebf337a_iv
  -in travis-deploy.enc -out travis-deploy -d
- chmod 600 travis-deploy
- mv travis-deploy ~/.ssh/id_rsa
script:
- docker-compose -f docker-compose.test.yml build
- docker-compose -f docker-compose.test.yml up --abort-on-container-exit
after_success:
  - bash deploy.sh
