sudo: required
language: python
python:
- '2.7'
addons:
  ssh_known_hosts: beer.list.api
services: docker
before_install:
- openssl aes-256-cbc -K $encrypted_8fab0ebf337a_key -iv $encrypted_8fab0ebf337a_iv
  -in travis_rsa.enc -out travis_rsa -d
- chmod 600 travis_rsa
- mv travis_rsa ~/.ssh/id_rsa
script:
- docker-compose -f docker-compose.test.yml build
- docker-compose -f docker-compose.test.yml up --abort-on-container-exit
after_success:
- bash deploy.sh
