FROM python:2.7
ADD requirements.txt /app/requirements.txt
ENV PYTHONDONTWRITEBYTECODE True
ENV FLASK_CONFIG production
WORKDIR /app
RUN pip install -r requirements.txt
ADD . /app
ADD ../beer-variables.env /app/beer-variables.env