FROM python:2.7
ADD requirements.txt /app/requirements.txt
ADD requirements_test.txt /app/requirements_test.txt
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE True
ENV FLASK_CONFIG testing
RUN pip install -r requirements.txt
RUN pip install -r requirements_test.txt
ADD . /app