web:
  build: .
  dockerfile: Dockerfile.test
  command: bash -c "py.test tests -vrsx --cov app --pylama && coveralls"
  ports:
    - "5000:5000"
  volumes:
    - .:/app
  links:
    - db
db:
  image: mongo