web:
  build: .
  dockerfile: Dockerfile.dev
  command: python -u manage.py startDevServer
  ports:
    - "5000:5000"
  volumes:
    - .:/app
  links:
    - db
db:
  image: mongo
  volumes:
    - ./data/db:/data/db