FROM python:2.7
ADD requirements.txt /app/requirements.txt
ENV PYTHONDONTWRITEBYTECODE True
ENV PYTHONUNBUFFERED 0
ENV FLASK_CONFIG development
WORKDIR /app
RUN pip install -r requirements.txt
ADD . /app